function createfigure(X1, Y1, Z1, S1, C1, X2, Y2, Z2, C2)
%CREATEFIGURE(X1, Y1, Z1, S1, C1, X2, Y2, Z2, C2)
%  X1:  scatter3 x
%  Y1:  scatter3 y
%  Z1:  scatter3 z
%  S1:  scatter3 s
%  C1:  scatter3 c
%  X2:  scatter3 x
%  Y2:  scatter3 y
%  Z2:  scatter3 z
%  C2:  scatter3 c

%  Auto-generated by MATLAB on 22-Sep-2015 18:20:06

% Create figure
figure1 = figure('PaperSize',[28.98404194812 29.67743169791]);

% Create axes
axes1 = axes('Parent',figure1,'FontSize',14);
view(axes1,[-3.5 12]);
grid(axes1,'on');
hold(axes1,'all');

% Create scatter3
scatter3(X1,Y1,Z1,S1,C1);

% Create scatter3
scatter3(X2,Y2,Z2,S1,C2,'Marker','+');

% Create title
title({'Undersampling on 3D data'});

